[env:rak11300]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rakwireless_rak11300
framework = arduino
board_build.core = earlephilhower

build_flags = 
    -D PICO_USB
    -D USBCON
    -D RAK11300
    -D WB_IO2=25
    -D PIN_WIRE_SDA=6
    -D PIN_WIRE_SCL=7
    -D REGION_EU868

monitor_speed = 115200

lib_deps = 
    sparkfun/SparkFun SHTC3 Humidity and Temperature Sensor Library @ ^1.1.4
    beegee-tokyo/SX126x-Arduino @ ^2.0.32
    Wire